name: On push
on:
    push:
        branches:
            - main
        paths:
            - 'package.json'

jobs:
   publish:
     name: Publish to Microsoft
     runs-on: ubuntu-latest
     environment: production
     steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '18'

       - name: Install dependencies
         run: npm install

       - name: Package extension
         run: |
           npm run package
           echo "VSIX_FILE=$(ls *.vsix)" >> $GITHUB_ENV

       - name: Publish to Marketplace
         uses: HaaLeo/publish-vscode-extension@v2
         with:
           pat: ${{ secrets.MICROSOFT_TOKEN }}
           packagePath: "${{ env.VSIX_FILE }}"
         working-directory: .
