name: On push
on:
    push:
        branches:
            - main

jobs:
   publish:
     name: Publish to Microsoft
     runs-on: ubuntu-latest
     environment: production
     steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '18'

       - name: Install dependencies
         run: npm install

       - name: Package extension
         run: npm run package

       - name: Login to VS Code Marketplace
         run: echo "${{ secrets.MICROSOFT_TOKEN }}" | npx vsce login r1cco

       - name: Publish to VS Code Marketplace
         run: npx vsce publish
